name: Qodana Scan
run-name: Qodana Scan ðŸ“¡
on:
  push:
    branches:
      - main

jobs:
  qodana-scan:
    runs-on: ubuntu-latest
    name: Run Qodana Scan
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Qodana Scan
        uses: JetBrains/qodana-action@main
        env:
          QODANA_TOKEN: ${{ secrets.QODANA_TOKEN }}
        with:
          exclude: Eslint,CommaExpressionJS